language: python

python:
  - 2.7
  - 3.4
  - 3.5

services:
  - postgresql
  - memcached

env:
  global:
  - DJANGO_SETTINGS_MODULE="bokaru.settings"
  - PYTHONPATH="/home/travis/build/bokaru/bokaru"
  - DATABASE_URL="postgres://localhost/bokaru"

install:
  - pip install -r requirements.txt
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - sudo service postgresql restart

before_script:
  - psql -c "CREATE DATABASE bokaru;" -U postgres
  - psql -U postgres -c "create extension postgis"
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test