language: python

dist: precise

python:
  - 3.4
  - 3.5
  - 3.6

services:
  - postgresql
  - memcached

env:
  global:
  - DJANGO_SETTINGS_MODULE="bokaru.settings.dev"
  - PYTHONPATH="/home/travis/build/bokaru/bokaru"
  - DATABASE_URL="postgres://localhost/bokaru"

install:
  - pip install -r requirements/common.txt
  - pip install -r requirements/dev.txt

before_script:
  - psql -c "CREATE ROLE bokaru WITH LOGIN SUPERUSER PASSWORD 'bokaru123'" -U postgres
  - psql -c "CREATE DATABASE bokaru WITH OWNER bokaru" -U postgres
  - psql -U postgres -c "create extension postgis"
  - cp env.dev.json env.json
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test
