language: python

python:
  - 2.7
  - 3.4
  - 3.5

services: postgresql

env:
  global:
  - DJANGO_SETTINGS_MODULE="bokaru.settings"
  - PYTHONPATH="/home/travis/build/bokaru/bokaru"
  - PIP_USE_MIRRORS=true
  - DATABASE_URL="postgres://localhost/bokaru"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE bokaru;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test